from task1 import grams
from task2 import convertion
from task3 import solve
from task4 import is_prime
from task5 import printpermutations
from task6 import reverse_sentence
from task7 import has_33
from task8 import spy_game
from task9 import sphere_volume
from task10 import unique_elements
from task11 import is_palindrome
from task12 import histogram
from task13 import guess_the_number
